# Generated by Django 5.2.8 on 2025-11-05 17:51

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of the emission data (1900-current year)', validators=[django.core.validators.MinValueValidator(1900, message='Year must be 1900 or later'), django.core.validators.MaxValueValidator(2025, message='Year cannot be in the future')])),
                ('emissions', models.DecimalField(decimal_places=3, help_text='Total emissions in metric tons (must be non-negative)', max_digits=15, validators=[django.core.validators.MinValueValidator(0.0, message='Emissions cannot be negative')])),
                ('emission_type', models.CharField(choices=[('CO2', 'Carbon Dioxide'), ('CH4', 'Methane'), ('N2O', 'Nitrous Oxide'), ('F_GASES', 'Fluorinated Gases')], help_text='Type of greenhouse gas emitted', max_length=10)),
                ('country', django_countries.fields.CountryField(help_text='Country where the emissions were recorded (ISO 3166-1 format)', max_length=2)),
                ('activity', models.CharField(choices=[('ENERGY', 'Energy Production'), ('TRANSPORT', 'Transportation'), ('INDUSTRY', 'Industrial Processes'), ('AGRICULTURE', 'Agriculture'), ('WASTE', 'Waste Management'), ('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('AIR_TRAVEL', 'Air Travel'), ('MARITIME', 'Maritime Transport'), ('OTHER', 'Other')], help_text='Activity sector responsible for the emissions', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
            options={
                'verbose_name': 'Emission',
                'verbose_name_plural': 'Emissions',
                'ordering': ['-year', 'country', 'emission_type'],
                'permissions': [('can_import_bulk_data', 'Can import bulk emission data'), ('can_export_data', 'Can export emission data'), ('can_view_audit_trail', 'Can view audit trail information')],
                'indexes': [models.Index(fields=['year'], name='idx_emission_year'), models.Index(fields=['country'], name='idx_emission_country'), models.Index(fields=['emission_type'], name='idx_emission_type'), models.Index(fields=['emissions'], name='idx_emission_value'), models.Index(fields=['year', 'country'], name='idx_year_country'), models.Index(fields=['country', 'emission_type'], name='idx_country_type'), models.Index(fields=['year', 'country', 'emission_type'], name='idx_year_country_type'), models.Index(fields=['activity', 'year'], name='idx_activity_year'), models.Index(fields=['-year', 'country'], name='idx_year_desc_country'), models.Index(fields=['-created_at'], name='idx_created_desc')],
                'constraints': [models.UniqueConstraint(fields=('year', 'country', 'emission_type', 'activity'), name='unique_emission_record', violation_error_message='An emission record for this year, country, type, and activity combination already exists.'), models.CheckConstraint(condition=models.Q(('emissions__gte', 0)), name='check_emissions_non_negative', violation_error_message='Emissions value must be non-negative.')],
            },
        ),
    ]
